on: push
name: Deploy FTP
jobs:
  web-deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout GitHub action script
        uses: actions/checkout@v3

      - name: Use Node.js 21
        uses: actions/setup-node@v2
        with:
          node-version: '21'

      - name: Build Project
        run: |
          npm install
          npm run build

      - name: Sync files
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: minervasolution.fr
          username: ${{ secrets.FTP_USER }}
          password: ${{ secrets.FTP_PASS }}